doc-warnings: no
test-warnings: no
strictness: medium
max-line-length: 120
uses:
    - wxPython
    - PySide
autodetect: yes
ignore-paths:
    - doc
    - pkg
ignore-patterns:
    - ^src/addons/Display/wx.*\.py$
    - ^src/addons/Display/py.*\.py$
    - ^src/addons/Display/Simple.*\.py$
